name: Fumotoppara Watch (Messaging API)

on:
  schedule:
    - cron: "*/10 * * * *"   # 10分ごと（UTC）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install playwright requests
          python -m playwright install --with-deps chromium
      - name: Run watcher
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          TARGET_DATE_LABELS: "11/1,11/2"   # ← ここで複数日を指定
          TARGET_ROWS: "キャンプ宿泊,キャンプ日帰り"
          TIMEOUT_MS: "60000"
        run: |
          python watch_fumotoppara.py   # ← あなたのファイル名に合わせる
